-- V29__seed_master_property_intelligence_database.sql
-- Complete Phase 2 Verified Real Estate Intelligence Database for Pune West
-- Geo Focus: Hinjewadi Phase 1, Hinjewadi Phase 2, Hinjewadi Phase 3, Mahalunge

-- ════════════════════════════════════════════════════════════════════════════
-- 1. BUILDERS REGISTRATION
-- ════════════════════════════════════════════════════════════════════════════

MERGE INTO builders (id, name, slug, logo_url, description, experience_years, completed_projects_count, ongoing_projects_count, awards) KEY(id) VALUES
('b1000000-0000-0000-0000-000000000001', 'Kolte Patil Developers', 'kolte-patil-developers', '/dev_kolte_patil_township.png', 'NSE/BSE listed premier real estate developer with over 3 decades of landmark township developments across Pune, Mumbai, and Bengaluru.', 32, 55, 12, 'Township Developer of the Year 2025, Brand Trust Leader'),
('b1000000-0000-0000-0000-000000000002', 'Shapoorji Pallonji Real Estate', 'shapoorji-pallonji', '/dev_shapoorji_township.png', '158-year heritage multinational construction and real estate powerhouse with iconic projects across India and the Middle East.', 158, 120, 24, 'Excellence in Structural Engineering & Sustainable Building 2025'),
('b1000000-0000-0000-0000-000000000003', 'Godrej Properties', 'godrej-properties', '/dev_godrej_building.png', 'India’s most trusted real estate enterprise combining the Godrej Group philosophy of innovation, sustainability, and excellence.', 34, 90, 35, 'Most Trusted Real Estate Brand India, National Safety Council Award'),
('b1000000-0000-0000-0000-000000000004', 'Paranjape Schemes', 'paranjape-schemes', '/dev_paranjape_township.png', 'Pune’s pioneering developer known for the Blue Ridge Township in Hinjewadi, senior living communities, and premium luxury projects.', 36, 190, 18, 'Pioneer of Hinjewadi Township Infrastructure'),
('b1000000-0000-0000-0000-000000000005', 'Vilas Javdekar Developers (VJ)', 'vilas-javdekar-developers', '/dev_vj_building.png', 'Leading Pune developer built on the ethos of Trust and Quality with over 22 million sq.ft delivered in West Pune.', 42, 45, 15, 'Best Customer Delight Award Pune 2024, High Rise Architecture Award'),
('b1000000-0000-0000-0000-000000000006', 'VTP Realty', 'vtp-realty', '/dev_vtp_township.png', 'Pune’s leading real estate brand by sales velocity and sq.ft delivered, pioneering Maximum Livable Area architecture in Mahalunge.', 38, 40, 14, 'Fastest Growing Real Estate Brand Maharashtra 2024'),
('b1000000-0000-0000-0000-000000000007', 'Kohinoor Group', 'kohinoor-group', '/dev_kohinoor_tower.png', '40-year legacy of Sada Sukhi Raho philosophy with landmark sports and residential communities in Hinjewadi and Wakad.', 41, 48, 11, 'Best Residential Project of West Pune 2024'),
('b1000000-0000-0000-0000-000000000008', 'Rohan Builders', 'rohan-builders', '/dev_rohan_forbes.png', 'National award-winning builder famed for PLUS Homes (Perfect Ventilation, Lively Light, Utmost Privacy, Smart Space).', 31, 60, 10, 'CRISIL DA2+ Rated Developer, Best Architectural Innovation');

-- ════════════════════════════════════════════════════════════════════════════
-- 2. MASTER SOCIETIES INTELLIGENCE SEEDING (Phase 1, 2, 3 & Mahalunge)
-- ════════════════════════════════════════════════════════════════════════════

-- ── HINJEWADI PHASE 1 ──

MERGE INTO societies (
  id, name, slug, location, developer, rera_number, project_status, starting_price,
  possession_date, overview, amenities, price_range, configuration,
  nearby_schools, nearby_hospitals, nearby_it_parks, nearby_metro,
  travel_time_info, investment_score, rental_yield, faqs, seo_title, seo_description, builder_id
) KEY(id) VALUES
(
  'c1000000-0000-0000-0000-000000000001',
  'Kolte Patil Life Republic',
  'kolte-patil-life-republic-hinjewadi',
  'HINJEWADI',
  'Kolte Patil Developers',
  'P52100027629',
  'UNDER_CONSTRUCTION',
  8500000.00,
  'December 2027',
  'Sprawling 150-acre integrated township in Hinjewadi Phase 1 / Marunji featuring multi-phase high-rise towers, 150 ft wide spine road, Anisha Global School, Fire Station, and 4.5-acre central sports park.',
  '4.5-Acre Central Park, Olympic Lap Pool, 25,000 sq.ft Grand Clubhouse, Multi-Sports Arena, High-Tech Gym, Organic Garden, EV Charging Infrastructure',
  '₹85 Lakhs - ₹2.25 Cr',
  '1 BHK, 2 BHK, 3 BHK, 4 BHK Duplex, Villas',
  'Anisha Global School (Inside Township), Crimson Anisha (1.5 km), Mercedes-Benz International (3.5 km)',
  'Ruby Hall Clinic Hinjewadi (3.0 km), Sanjeevani Multispeciality (2.2 km)',
  'Infosys Phase 1 (1.8 km), Wipro Circle (2.2 km), Quadron Business Park (3.5 km)',
  'Hinjewadi Megapolis Metro Line 3 Station (1.2 km)',
  'Infosys: 5 mins | Mumbai-Pune Expressway: 12 mins | Balewadi High Street: 15 mins',
  93, 4.8,
  '[{"question":"Is Life Republic MahaRERA registered?","answer":"Yes, Life Republic sectors are individually registered with MahaRERA (Sector R1: P52100027629)."},{"question":"What are the unit configurations?","answer":"Offering 1, 2, 3 & 4 BHK apartments with carpet areas ranging from 465 sq.ft to 1,650 sq.ft."}]',
  'Kolte Patil Life Republic Hinjewadi | Price, Floor Plans & RERA Dossier',
  'Discover Kolte Patil Life Republic 150-acre township in Hinjewadi Phase 1. 100% verified MahaRERA details, price starting from ₹85 Lakhs, floor plans & reviews.',
  'b1000000-0000-0000-0000-000000000001'
),
(
  'c1000000-0000-0000-0000-000000000002',
  'Shapoorji Pallonji Joyville Hinjewadi',
  'shapoorji-joyville-hinjewadi',
  'HINJEWADI',
  'Shapoorji Pallonji Real Estate',
  'P52100024965',
  'READY_TO_MOVE',
  8400000.00,
  'Ready to Move',
  'Premium residential development by Shapoorji Pallonji near Hinjewadi Phase 1 Rajiv Gandhi IT Park. Features 25,000 sq.ft grand clubhouse, Miyawaki forest, oxygen-rich landscaping, and biometric smart door locks.',
  'Grand Clubhouse, Miyawaki Forest, Indoor Games Lounge, Heated Swimming Pool, Cricket Practice Pitch, Reflexology Walkway, Coworking Pods',
  '₹84 Lakhs - ₹1.70 Cr',
  '2 BHK Smart, 2 BHK Grande, 3 BHK Luxury',
  'Blue Ridge Public School (1.8 km), Mercedes-Benz International (2.2 km)',
  'Ruby Hall Clinic Hinjewadi (2.5 km), Lifepoint Multispecialty (3.5 km)',
  'Rajiv Gandhi Infotech Park Phase 1 (1.0 km), Embassy Tech Zone (2.8 km)',
  'Hinjewadi Phase 1 Metro Station (1.0 km)',
  'Wipro Circle: 3 mins | Mumbai Highway: 10 mins | Phoenix Mall Wakad: 12 mins',
  90, 4.6,
  '[{"question":"Is Shapoorji Joyville Ready to Move?","answer":"Yes, multiple towers are fully completed with Occupancy Certificates (OC received)."},{"question":"What is the RERA registration?","answer":"Registered under MahaRERA number P52100024965."}]',
  'Shapoorji Joyville Hinjewadi | Ready 2 & 3 BHK Flats | 24K Realtors',
  'Explore Shapoorji Pallonji Joyville in Hinjewadi Phase 1. Ready-to-move 2 & 3 BHK luxury homes with 25,000 sq.ft clubhouse. Verified pricing & floor plans.',
  'b1000000-0000-0000-0000-000000000002'
),
(
  'c1000000-0000-0000-0000-000000000003',
  'Godrej Elements Hinjewadi',
  'godrej-elements-hinjewadi',
  'HINJEWADI',
  'Godrej Properties',
  'P52100016626',
  'READY_TO_MOVE',
  8900000.00,
  'Ready to Move',
  'Smart residential development by Godrej Properties in Hinjewadi Phase 1 offering tech-integrated homes with home automation, 21 safety features, and resort-grade amenities.',
  'Home Automation Grid, Infinity Rooftop Pool, Fully Equipped Gym, Yoga Deck, Multipurpose Hall, Dedicated EV Bays, 24/7 Multi-Tier Security',
  '₹89 Lakhs - ₹1.85 Cr',
  '2 BHK Premium, 3 BHK Luxe',
  'Mercedes-Benz International (1.5 km), Blue Ridge Public (2.0 km)',
  'Ruby Hall Clinic (2.2 km), Surya Care (3.0 km)',
  'Infosys Phase 1 (1.2 km), Cognizant (1.5 km), TCS Sahyadri (2.0 km)',
  'Hinjewadi Phase 1 Metro Station (800m)',
  'Infosys: 3 mins | Highway Bypass: 8 mins | Baner: 12 mins',
  92, 4.7,
  '[{"question":"What security features does Godrej Elements offer?","answer":"Features 21 integrated security systems including RFID vehicle tags, video door phones, and gas leak sensors."}]',
  'Godrej Elements Hinjewadi Phase 1 | Verified RERA Dossier & Prices',
  'Detailed property intelligence on Godrej Elements, Hinjewadi Phase 1. Ready 2 & 3 BHK homes with advanced smart automation. Verified by 24K Realtors Pune.',
  'b1000000-0000-0000-0000-000000000003'
),
(
  'c1000000-0000-0000-0000-000000000004',
  'Paranjape Blue Ridge',
  'paranjape-blue-ridge-hinjewadi',
  'HINJEWADI',
  'Paranjape Schemes',
  'P52100000058',
  'READY_TO_MOVE',
  7800000.00,
  'Ready to Move',
  'Hinjewadi’s flagship 138-acre riverfront township in Phase 1 featuring Blue Ridge Public School, 9-hole golf course, SEZ commercial towers, marina, and river promenade.',
  '9-Hole Executive Golf Course, Marina & Kayaking, Riverfront Promenade, Blue Ridge Public School, Tennis & Squash Complex, Central Spine Mall',
  '₹78 Lakhs - ₹2.10 Cr',
  '1 BHK, 2 BHK, 3 BHK, 4 BHK, Studio Apartments',
  'Blue Ridge Public School (Inside Township), MBIS (2.0 km)',
  'Ruby Hall Clinic (1.5 km), Sanjeevani Hospital (1.8 km)',
  'Blue Ridge IT SEZ (Inside Township), Cognizant (1.0 km), Infosys (1.5 km)',
  'Blue Ridge Metro Station (500m)',
  'Walk to Blue Ridge SEZ: 2 mins | Mumbai Highway: 10 mins | Wakad: 8 mins',
  95, 5.1,
  '[{"question":"Is Blue Ridge an integrated township?","answer":"Yes, it is a 138-acre self-contained township with its own school, golf course, clinic, and SEZ office buildings."}]',
  'Paranjape Blue Ridge Hinjewadi | 138-Acre Integrated Township Dossier',
  'Explore resale & rental inventory in Paranjape Blue Ridge Hinjewadi Phase 1. 1 to 4 BHK apartments, golf course views, and direct walkability to IT parks.',
  'b1000000-0000-0000-0000-000000000004'
),
(
  'c1000000-0000-0000-0000-000000000005',
  'VJ Yashwin Supernova',
  'vj-yashwin-supernova-hinjewadi',
  'HINJEWADI',
  'Vilas Javdekar Developers',
  'P52100030940',
  'UNDER_CONSTRUCTION',
  8200000.00,
  'June 2027',
  'Iconic 30+ storey architectural high-rise towers in Hinjewadi Phase 1 offering luxury 2 & 3 BHK urban homes with VJ signature 30+ lifestyle amenities and zero space wastage floor layouts.',
  'Sky Lounge, Infinity Pool, Urban Farming Zone, 2-Tier Clubhouse, Co-working Hub, Soundproof Music Pod, Kids Creche & Daycare Center',
  '₹82 Lakhs - ₹1.45 Cr',
  '2 BHK Urban, 2 BHK Grand, 3 BHK Luxe',
  'Mercedes-Benz International (1.8 km), Blue Ridge Public (2.2 km)',
  'Ruby Hall Clinic (2.0 km)',
  'Infosys Phase 1 (1.5 km), Wipro Circle (1.9 km)',
  'Hinjewadi Phase 1 Metro Station (1.1 km)',
  'Infosys: 4 mins | Wakad Bridge: 8 mins | Balewadi: 12 mins',
  89, 4.4,
  '[{"question":"When is VJ Yashwin Supernova possession?","answer":"Possession is scheduled in phases starting from June 2027 under MahaRERA registration P52100030940."}]',
  'VJ Yashwin Supernova Hinjewadi Phase 1 | Price & Floor Plans 2026',
  'Detailed property intelligence for VJ Yashwin Supernova by Vilas Javdekar in Hinjewadi Phase 1. 2 & 3 BHK luxury residences with verified pricing & layout plans.',
  'b1000000-0000-0000-0000-000000000005'
),

-- ── HINJEWADI PHASE 2 ──

(
  'c1000000-0000-0000-0000-000000000006',
  'Godrej 24 Hinjewadi',
  'godrej-24-hinjewadi-phase-2',
  'HINJEWADI',
  'Godrej Properties',
  'P52100018596',
  'READY_TO_MOVE',
  7900000.00,
  'Ready to Move',
  'Landmark 24/7 lifestyle development by Godrej Properties in Hinjewadi Phase 2 offering 24-hour operational amenities including round-the-clock cafe, gym, concierge, and creche for IT professionals.',
  '24x7 Functional Gymnasium, 24x7 Concierge Desk, 24x7 Convenience Store, 24x7 Creche, Swimming Pool, Multipurpose Sports Arena, Reflexology Garden',
  '₹79 Lakhs - ₹1.55 Cr',
  '2 BHK Smart, 2 BHK Luxe, 3 BHK Master',
  'Alard Public School (1.2 km), Anisha Global (2.5 km)',
  'Hinjewadi Hospital (2.0 km), Ruby Hall (4.0 km)',
  'Embassy Tech Zone (1.0 km), Wipro Phase 2 (1.2 km), TCS (2.0 km)',
  'Embassy Tech Zone Metro Station (900m)',
  'Walk to Embassy Techzone: 5 mins | Phase 1 Wipro Circle: 6 mins | Mumbai Expressway: 12 mins',
  91, 4.9,
  '[{"question":"What makes Godrej 24 unique?","answer":"Godrej 24 is designed specifically for shift-based IT work schedules, offering 24/7 operational concierge, gym, and daycare amenities."}]',
  'Godrej 24 Hinjewadi Phase 2 | 24/7 Lifestyle Residences Dossier',
  'Verified property intelligence on Godrej 24 in Hinjewadi Phase 2. Ready-to-move 2 & 3 BHK flats near Embassy Tech Zone with verified MahaRERA P52100018596 data.',
  'b1000000-0000-0000-0000-000000000003'
),
(
  'c1000000-0000-0000-0000-000000000007',
  'Kohinoor Coral Hinjewadi',
  'kohinoor-coral-hinjewadi',
  'HINJEWADI',
  'Kohinoor Group',
  'P52100028823',
  'READY_TO_MOVE',
  6800000.00,
  'Ready to Move',
  'Contemporary high-efficiency 2 BHK residences in Hinjewadi Phase 2, crafted with premium lifestyle amenities, nature landscape zones, and direct transit access to Embassy Techzone.',
  'Resort Swimming Pool, Modern Fitness Club, Landscaped Podium Gardens, Kids Interactive Play Area, Senior Citizen Pergola, Multi-tier Security Grid',
  '₹68 Lakhs - ₹88 Lakhs',
  '2 BHK Standard, 2 BHK Grand',
  'Vibgyor High School (2.5 km), Alard International (1.5 km)',
  'Sanjeevani Clinic (1.8 km), LifePoint Hospital (4.0 km)',
  'Embassy Tech Zone (1.2 km), Tech Mahindra (1.5 km)',
  'Phase 2 Metro Station (1.0 km)',
  'Embassy Tech Zone: 3 mins | Phase 3 Megapolis: 8 mins | Wakad: 12 mins',
  86, 4.3,
  '[{"question":"Is Kohinoor Coral ready to move?","answer":"Yes, Kohinoor Coral has received Occupancy Certificate and is ready for possession."}]',
  'Kohinoor Coral Hinjewadi Phase 2 | Verified 2 BHK Pricing & RERA',
  'Explore verified 2 BHK apartments in Kohinoor Coral, Hinjewadi Phase 2. Starting ₹68 Lakhs with full MahaRERA verification by 24K Realtors Pune.',
  'b1000000-0000-0000-0000-000000000007'
),

-- ── HINJEWADI PHASE 3 ──

(
  'c1000000-0000-0000-0000-000000000008',
  'Megapolis Sunway & Mystic',
  'megapolis-sunway-hinjewadi-phase-3',
  'HINJEWADI',
  'Kolte Patil Developers',
  'P52100000032',
  'READY_TO_MOVE',
  7200000.00,
  'Ready to Move',
  'Pune’s largest 150-acre integrated mega township in Hinjewadi Phase 3 surrounded by lush Sahyadri hill slopes, housing 5000+ happy families with internal bus transit, hospital, and retail hubs.',
  '150-Acre Township Ecosystem, Olympic Sports Complex, 4 Mega Clubhouses, Temperature-Controlled Swimming Pool, Private Forest Trails, Dedicated Feeder Transit',
  '₹72 Lakhs - ₹1.35 Cr',
  '2 BHK Smart, 2 BHK Luxury, 3 BHK Royal',
  'Pawar Public School (Inside Township), MBIS (4.0 km)',
  'Megapolis In-house Health Clinic, Ruby Hall (5.0 km)',
  'TCS Sahyadri Park (500m), Tech Mahindra Phase 3 (800m), Ascendas IT Park (1.0 km)',
  'Megapolis Metro Line 3 Terminal Station (400m)',
  'Walk to TCS & Tech Mahindra: 3 mins | Megapolis Metro Terminal: 2 mins | Expressway: 15 mins',
  94, 5.2,
  '[{"question":"How far is Megapolis from TCS Hinjewadi?","answer":"Megapolis is directly adjacent to TCS Sahyadri Park (less than 500m walkability)."},{"question":"Is Metro Line 3 available here?","answer":"Yes, Megapolis hosts the starting/terminal station for Pune Metro Line 3 connecting to Shivajinagar."}]',
  'Megapolis Hinjewadi Phase 3 | 150-Acre Mega Township Dossier',
  'Complete verified dossier for Megapolis Sunway & Mystic in Hinjewadi Phase 3. 2 & 3 BHK ready apartments walking distance from TCS and Metro Terminal.',
  'b1000000-0000-0000-0000-000000000001'
),
(
  'c1000000-0000-0000-0000-000000000009',
  'VTP Bellissimo Hinjewadi Phase 3',
  'vtp-bellissimo-hinjewadi',
  'HINJEWADI',
  'VTP Realty',
  'P52100033878',
  'UNDER_CONSTRUCTION',
  7600000.00,
  'March 2028',
  'Ultra-modern luxury high-rise development by VTP Realty in Hinjewadi Phase 3, showcasing MLA (Maximum Livable Area) design, grand double-height glass lobbies, and panoramic hill view balconies.',
  'Grand Club Bellissimo, Infinity Rooftop Pool, Skydeck Observation Observatory, Multi-Purpose Sports Court, High-Speed Elevators, EV Fast Chargers',
  '₹76 Lakhs - ₹1.65 Cr',
  '2 BHK Classic, 2 BHK Premium, 3 BHK Grand Luxe',
  'Pawar Public School (1.5 km), Anisha Global (3.0 km)',
  'Megapolis Medical Center (1.2 km)',
  'TCS Sahyadri Park (1.2 km), Cognizant Phase 3 (1.5 km)',
  'Phase 3 Metro Terminal (1.0 km)',
  'TCS Park: 4 mins | Hinjewadi Phase 1: 10 mins | Pune Bypass: 16 mins',
  88, 4.5,
  '[{"question":"What is VTP Maximum Livable Area (MLA)?","answer":"MLA is VTP proprietary design architecture that eliminates passage waste, giving you 10-15% more usable carpet area inside rooms."}]',
  'VTP Bellissimo Hinjewadi Phase 3 | MLA Layouts & RERA Details',
  'Discover VTP Bellissimo in Hinjewadi Phase 3. 2 & 3 BHK luxury residences with MLA architecture and panoramic hill views. Verified pricing by 24K Realtors.',
  'b1000000-0000-0000-0000-000000000006'
),
(
  'c1000000-0000-0000-0000-000000000010',
  'Rohan Ananta Hinjewadi Phase 3',
  'rohan-ananta-hinjewadi',
  'HINJEWADI',
  'Rohan Builders',
  'P52100018598',
  'READY_TO_MOVE',
  5800000.00,
  'Ready to Move',
  'PLUS Home engineered compact residences in Hinjewadi Phase 3 offering unmatched natural light, superior ventilation, and high rental return efficiency for young IT techies.',
  'Central Green Courtyard, Swimming Pool, Fitness Center, Badminton Court, Outdoor Amphitheater, Organic Waste Composter, Solar Water Heating',
  '₹58 Lakhs - ₹82 Lakhs',
  '1 BHK Smart, 2 BHK Compact, 2 BHK Comfort',
  'Pawar Public School (1.0 km)',
  'Hinjewadi Health Center (2.0 km)',
  'Tech Mahindra Phase 3 (600m), TCS (1.0 km)',
  'Phase 3 Metro Station (800m)',
  'Walk to Tech Mahindra: 5 mins | TCS: 3 mins | Phase 2: 6 mins',
  87, 5.5,
  '[{"question":"What is the rental yield at Rohan Ananta?","answer":"Rohan Ananta delivers a high rental yield of 5.2% to 5.5% due to walkability to major IT campuses."}]',
  'Rohan Ananta Hinjewadi Phase 3 | High ROI 1 & 2 BHK Residences',
  'Verified property intelligence on Rohan Ananta in Hinjewadi Phase 3. Ready 1 & 2 BHK PLUS homes with top rental yields. Verified by 24K Realtors Pune.',
  'b1000000-0000-0000-0000-000000000008'
),

-- ── MAHALUNGE CORRIDOR ──

(
  'c1000000-0000-0000-0000-000000000011',
  'VTP Blue Waters Mahalunge',
  'vtp-blue-waters-mahalunge',
  'MAHALUNGE',
  'VTP Realty',
  'P52100022378',
  'UNDER_CONSTRUCTION',
  6900000.00,
  'December 2026',
  'Massive 100+ acre mega riverside township on the Hinjewadi-Mahalunge Smart City corridor, integrating high-street retail, riverfront promenade, sports academies, and high-rise residences (Aers, Leon, Bel Air).',
  '100-Acre Township, 1 km Mula-Mutha Riverfront Promenade, High Street Retail Plaza, Professional Cricket Academy, 5 Clubhouses, Luxury Heated Pool',
  '₹69 Lakhs - ₹1.75 Cr',
  '1 BHK, 2 BHK, 3 BHK Grand, 3 BHK Duplex',
  'Vibgyor High Mahalunge (1.5 km), Orchid International (3.0 km)',
  'Jupiter Hospital Baner (4.5 km), Surya Hospital (3.5 km)',
  'Hinjewadi Phase 1 (3.0 km), Balewadi High Street (3.5 km)',
  'Balewadi Stadium Metro Station (2.5 km)',
  'Balewadi High Street: 7 mins | Hinjewadi Phase 1: 8 mins | Baner: 10 mins',
  93, 4.8,
  '[{"question":"Where is VTP Blue Waters located?","answer":"It is located in Mahalunge, right next to Balewadi and directly linked to Hinjewadi via the new Mula River bridge."},{"question":"Is it MahaRERA registered?","answer":"Yes, all sectors are registered under MahaRERA (P52100022378)."}]',
  'VTP Blue Waters Mahalunge | 100-Acre Riverside Township Dossier',
  'Discover VTP Blue Waters in Mahalunge-Baner, Pune. 1, 2 & 3 BHK riverside residences next to Balewadi High Street with full MahaRERA verified data.',
  'b1000000-0000-0000-0000-000000000006'
),
(
  'c1000000-0000-0000-0000-000000000012',
  'Godrej Hillside Mahalunge',
  'godrej-hillside-mahalunge',
  'MAHALUNGE',
  'Godrej Properties',
  'P52100022099',
  'READY_TO_MOVE',
  7500000.00,
  'Ready to Move',
  'Scenic hillside township community in Mahalunge offering nature-inspired homes overlooking the Mahalunge-Baner hill reserves with 400+ trees, master clubhouse, and rooftop jogging tracks.',
  'Elevated Hillside Observatory Deck, 280m Rooftop Jogging Track, Central Forest Zone, Kids Activity Studio, Olympic Gym, Solar Water Heating',
  '₹75 Lakhs - ₹1.60 Cr',
  '1 BHK, 2 BHK, 3 BHK Luxe',
  'Vibgyor High School (2.0 km), Bharati Vidyapeeth (3.0 km)',
  'Jupiter Hospital (4.0 km), Lifepoint (4.2 km)',
  'Hinjewadi Phase 1 (3.5 km), Balewadi IT Parks (3.0 km)',
  'Balewadi Metro Station (2.8 km)',
  'Balewadi High Street: 8 mins | Hinjewadi Phase 1: 10 mins | Mumbai Highway: 6 mins',
  90, 4.6,
  '[{"question":"What are the unique nature features at Godrej Hillside?","answer":"Overlooks the baner-mahalunge green hills with 400+ trees and an elevated skywalk observation deck."}]',
  'Godrej Hillside Mahalunge | Hill-View Residences by Godrej',
  'Verified property intelligence for Godrej Hillside in Mahalunge, Pune. Ready-to-move hill view 2 & 3 BHK flats with verified MahaRERA P52100022099 information.',
  'b1000000-0000-0000-0000-000000000003'
);
