CREATE TABLE whatsapp_message_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id UUID NOT NULL,
    phone VARCHAR(20) NOT NULL,
    template_name VARCHAR(255) NOT NULL,
    parameters_json TEXT,
    status VARCHAR(20) NOT NULL,
    error_message TEXT,
    payload_json TEXT,
    sent_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_wa_lead_id ON whatsapp_message_logs(lead_id);
CREATE INDEX idx_wa_sent_time ON whatsapp_message_logs(sent_timestamp);
